### ISSUE TITLE
Deleted newlines

### ISSUE THREAD

**Issue by nschneid** [amir-zeldes/DepEdit#22]
I am using DepEdit to modify the .conllu files in English-EWT. One annoyance is that those files end with a blank line that DepEdit deletes. I can hack it to add a newline at the end, but should it support this in a more principled way (e.g. preserve all blank lines outside sentences that are seen in the input)?

**Comment by amir-zeldes** [comment]
The intended behavior as I recall is to leave the trailing lines the way they were in the input, under the assumption that it's the users business how many blank lines they want. Can you give me the scenario you are running so I can debug? Is it a glob pattern from the command line, under Python 3.x?

**Comment by nschneid** [comment]
A glob pattern, yes. Either version of Python. Adding `+ "\n"` to

https://github.com/amir-zeldes/DepEdit/blob/c2a25ca83687a7d7a58bd6fcc0e5cf068b95b440/depedit/depedit.py#L803

is a hack that works to add a blank line at the end.

**Comment by nschneid** [comment]
Actually, maybe that's not a hack but the correct behavior: since all the contents of `output_lines` have whitespace stripped off, the last input line will be missing its final `\n`.
