### ISSUE TITLE
Empty node indices should not be floats

### ISSUE THREAD

**Issue by nschneid** [amir-zeldes/DepEdit#23]
When I run DepEdit on a files containing Enhanced UD ellipsis nodes, it replaces them as floats even if the rule does not affect the token. E.g.:

    7.1    found   find    VERB    VBD     Mood=Ind|Tense=Past|VerbForm=Fin        _       _       3:conj  CopyOf=3

Becomes

    7.100000000000001      found   find    VERB    VBD     Mood=Ind|Tense=Past|VerbForm=Fin        _       _       3:conj  CopyOf=3

**Comment by amir-zeldes** [comment]
Them being floats should make sense, since 7.1 is essentially a float, and we need to order the output nodes. The strange part is why 7.1 becomes 7.100....1 - that's not something Python should be doing, even if they are floats. Let me look into this.

**Comment by nschneid** [comment]
That's not Python-specific—it's standard for how floating point memory works (it doesn't represent fractional values exactly). Python does have the [`Decimal`](https://docs.python.org/3/library/decimal.html) type which solves that.

But really, it feels like a dirty hack because node 7.1 is not fractional in the sense of being 10% closer to 8 than 7 is. And you could conceivably have all the way up to 7.10, 7.11, etc. So it's really two integers separated by a dot. If they need to be compared for sorting, why not represent all the token indices as tuples?

```python
>>> sorted([(7,1), (7,), (7,10), (7,2)])
[(7,), (7, 1), (7, 2), (7, 10)]
```

**Comment by amir-zeldes** [comment]
Looking at this in the debugger, the reason I missed this is that none of this seems to happen under Windows... 

I any case, it doesn't really matter if it's a ratio scale as long as the output looks right. Since it's just an output issue, really this can be fixed in `serialize_output_tree`. I don't think we ever have more than 9 empty nodes on the same token, so we can just treat this as only one digit allowed past the decimal point. This should fix it with minimal changes: 1ea3156 .

I'll have a look at #22 before re-releasing.

**Comment by nschneid** [comment]
https://docs.python.org/3/tutorial/floatingpoint.html explains some of the issues with floats. Here's an example in my shell (I think the imprecision is triggered by subtraction but not addition/multiplication for some reason):

    $ python
    Python 3.7.3 (default, Mar 27 2019, 16:54:48)
    [Clang 4.0.1 (tags/RELEASE_401/final)] :: Anaconda, Inc. on darwin
    Type "help", "copyright", "credits" or "license" for more information.
    >>> float('20.2')-13
    7.199999999999999
    >>> 20.2-13
    7.199999999999999
    >>> from decimal import Decimal
    >>> Decimal('20.2')-13
    Decimal('7.2')
    >>> print(Decimal('20.2')-13)
    7.2

This may be a hardware- or OS-dependent. But the punchline is, never assume float arithmetic deals exactly with decimals.

**Comment by nschneid** [comment]
This is a dirty hack but it works:

```py
from decimal import Decimal as float
```
