### ISSUE TITLE
Head field is buggy

### ISSUE THREAD

**Issue by nschneid** [amir-zeldes/DepEdit#26]
The rule

- `lemma=/^[Tt]he$/&upostag=/^PROPN$/&head=/(.*)/`
- `none`
- `#1:upostag=DET;#1:xpostag=DT;#1:morph=Definite=Def|PronType=Art;#1:deprel=det;#1:deps=$1:amod`

Is putting 3-digit indices in the deps field where it should be the head index.

**Comment by amir-zeldes** [comment]
This is due to using the absolute token ID internally, will fix

**Comment by amir-zeldes** [comment]
Fixed in 2.1.7
