### ISSUE TITLE
Case-insensitive regex match

### ISSUE THREAD

**Issue by nschneid** [amir-zeldes/DepEdit#48]
How to do this? Given the Perl-like slash notation I expected an `i` flag to work:

`lemma=/(Dr|Mrs?|Ms|Fr|Sr|St|Lt|Sgt|Pvt|G\.?I)\.?/i`

The script executes without error but there are no matches.

**Comment by nschneid** [comment]
I figured out a way to specify an inline flag, but it took some effort to avoid an error when using it with a variable:

```
{honorific}=/(Lieutenant|Sergeant|Private|Miss|Mister|Doctor|Father|Sister|Saint|(Dr|Mrs?|Ms|Fr|Sr|St|Lt|Sgt|Pvt|G\.?I)\.?|Rev(erend|\.)?|Prof(essor|\.)?|Gov(ernor|\.)?|Sen(ator|\.)?|Gen(eral|\.)?|Maj(or|\.)?|Col(onel|\.)?|Capt(ain|\.)?|Adm(iral|\.)?)/

...

lemma=/(?i)({honorific})/
```

Note that `(?i)` is required to be at the very start of the regex pattern, and not adding the extra parentheses around the variable causes the TypeError of #47.

It would be helpful to add an example of case-insensitive matching in the docs, and to either add support for the post-slash flag or raise an error if it is not supported.

**Comment by amir-zeldes** [comment]
Yup, you got it - `(?i)` is the intended way, see for example [here](https://github.com/amir-zeldes/gum/blob/master/_build/utils/eng_enhance.ini#L202)

Supporting `/../i` would be nice, but this is really not Perl, and doing so might lead to people thinking that `/.../` does single replacements while `/.../g` does global or whatnot, so I'm not sure that's advisable. An error message and documentation would make sense. I can add it to the user guide for the next release.
